from .routine_directory import (
    Away,
    Breathe,
    Candle,
    Daylight,
    Disco,
    Fire,
    Focus,
    Iridescent,
    Lightning,
    Love,
    Movie,
    NightLight,
    Ocean,
    Party,
    Police,
    Rainbow,
    Sunset,
)
from .types import LightRoutine

ROUTINES: dict[str, type[LightRoutine]] = {
    Away.NAME: Away,
    Breathe.NAME: Breathe,
    Candle.NAME: Candle,
    Daylight.NAME: Daylight,
    Disco.NAME: Disco,
    Fire.NAME: Fire,
    Focus.NAME: Focus,
    Iridescent.NAME: Iridescent,
    Lightning.NAME: Lightning,
    Love.NAME: Love,
    Movie.NAME: Movie,
    NightLight.NAME: NightLight,
    Ocean.NAME: Ocean,
    Party.NAME: Party,
    Police.NAME: Police,
    Rainbow.NAME: Rainbow,
    Sunset.NAME: Sunset,
}
